package valthorne.graphics.texture;

import valthorne.graphics.shader.Shader;

/**
 * <h1>TextureBatchShader</h1>
 *
 * <p>
 * {@code TextureBatchShader} is a specialized {@link Shader} implementation designed to work directly
 * with {@link TextureBatch}. It automatically applies the attribute contract defined by
 * {@link TextureBatchContract}, reloads itself after binding those attribute locations, and binds all
 * texture sampler uniforms expected by the batch.
 * </p>
 *
 * <p>
 * This class exists so batch-compatible shaders can be created with minimal boilerplate. Instead of
 * manually remembering the required attribute names, sampler uniforms, and default fallback shader
 * sources, you can construct a {@code TextureBatchShader} and let it normalize everything for you.
 * </p>
 *
 * <h2>How fragment source works</h2>
 *
 * <p>
 * The fragment source can be supplied in two different modes:
 * </p>
 * <ul>
 *     <li>If {@code fullFragmentSource} is {@code false}, the provided fragment body is treated as a
 *     partial shader body and is prefixed with the standard batch fragment preamble generated by
 *     {@link TextureBatchContract#buildFragmentPreamble(int)}.</li>
 *     <li>If {@code fullFragmentSource} is {@code true}, the fragment source is treated as a complete,
 *     already-finished GLSL fragment shader and is used exactly as provided.</li>
 * </ul>
 *
 * <p>
 * This makes it easy to either write quick batch-aware effects using helper functions like
 * {@code sampleBatchTexture(...)} and {@code batchClipped()}, or provide a completely custom shader
 * when full control is needed.
 * </p>
 *
 * <h2>Vertex source behavior</h2>
 *
 * <p>
 * If no vertex shader source is supplied, the default batch vertex shader from
 * {@link TextureBatchContract#defaultVertexShader()} is used automatically.
 * </p>
 *
 * <h2>Typical usage</h2>
 *
 * <p>
 * The most common use case is creating a fragment effect while still using the default batch vertex
 * shader and batch sampler setup.
 * </p>
 *
 * <h2>Example</h2>
 * <pre>{@code
 * TextureBatchShader shader = new TextureBatchShader(
 *     8,
 *     """
 *     void main() {
 *         if (batchClipped()) discard;
 *
 *         vec4 color = sampleBatchTexture(v_uv);
 *         gl_FragColor = color * v_col;
 *     }
 *     """
 * );
 *
 * TextureBatch batch = new TextureBatch(4096, 8);
 * batch.begin();
 * batch.setShader(shader);
 * batch.draw(texture, 100f, 100f, 64f, 64f);
 * batch.end();
 * }</pre>
 *
 * @author Albert Beaupre
 * @since March 8th, 2026
 */
public class TextureBatchShader extends Shader {

    private final int maxTextureUnits; // The number of texture samplers this shader is built to support.

    /**
     * Creates a batch-compatible shader using the default batch vertex shader and default batch
     * fragment shader.
     *
     * <p>
     * This is the simplest constructor and is useful when you want a shader object that matches the
     * batch contract exactly without supplying any custom GLSL.
     * </p>
     *
     * @param maxTextureUnits the number of texture units the shader should support
     */
    public TextureBatchShader(int maxTextureUnits) {
        this(maxTextureUnits, null, null, false);
    }

    /**
     * Creates a batch-compatible shader using the default batch vertex shader and a custom fragment
     * shader source.
     *
     * <p>
     * The provided fragment source is treated as a partial fragment body and is automatically prefixed
     * with the batch fragment preamble unless a different constructor is used with
     * {@code fullFragmentSource = true}.
     * </p>
     *
     * @param maxTextureUnits the number of texture units the shader should support
     * @param fragmentSource  the custom fragment source body to append after the batch preamble
     */
    public TextureBatchShader(int maxTextureUnits, String fragmentSource) {
        this(maxTextureUnits, null, fragmentSource, false);
    }

    /**
     * Creates a batch-compatible shader using an optional custom vertex shader and an optional custom
     * fragment shader.
     *
     * <p>
     * The vertex source falls back to the default batch vertex shader when null or blank. The fragment
     * source falls back to the default batch fragment shader when null or blank. When a fragment source
     * is provided here, it is treated as a partial shader body and receives the batch preamble.
     * </p>
     *
     * @param maxTextureUnits the number of texture units the shader should support
     * @param vertexSource    the custom vertex shader source, or null to use the default batch vertex shader
     * @param fragmentSource  the custom fragment shader body, or null to use the default batch fragment shader
     */
    public TextureBatchShader(int maxTextureUnits, String vertexSource, String fragmentSource) {
        this(maxTextureUnits, vertexSource, fragmentSource, false);
    }

    /**
     * Creates a batch-compatible shader with full control over how the fragment source is interpreted.
     *
     * <p>
     * This constructor performs the complete setup required for batch compatibility:
     * </p>
     * <ul>
     *     <li>Normalizes the vertex source, falling back to the batch default when necessary</li>
     *     <li>Normalizes the fragment source, either building a default shader, prefixing the batch
     *     preamble, or using the source exactly as provided</li>
     *     <li>Binds all required batch attribute locations</li>
     *     <li>Reloads the shader so the attribute bindings take effect</li>
     *     <li>Binds all {@code u_texN} sampler uniforms for the requested texture unit count</li>
     * </ul>
     *
     * @param maxTextureUnits    the number of texture units the shader should support
     * @param vertexSource       the custom vertex shader source, or null to use the batch default
     * @param fragmentSource     the fragment shader source or body, depending on {@code fullFragmentSource}
     * @param fullFragmentSource true to treat {@code fragmentSource} as a complete fragment shader,
     *                           false to prefix the batch fragment preamble
     * @throws IllegalArgumentException if {@code maxTextureUnits < 1}
     * @throws IllegalStateException    if shader compilation or linking fails during reload
     */
    public TextureBatchShader(int maxTextureUnits, String vertexSource, String fragmentSource, boolean fullFragmentSource) {
        super(normalizeVertexSource(vertexSource), normalizeFragmentSource(fragmentSource, maxTextureUnits, fullFragmentSource));

        if (maxTextureUnits < 1) {
            throw new IllegalArgumentException("maxTextureUnits must be >= 1");
        }

        this.maxTextureUnits = maxTextureUnits;

        TextureBatchContract.bindAttributes(this);

        if (!reload()) {
            throw new IllegalStateException("Failed to reload TextureBatchShader.");
        }

        TextureBatchContract.bindSamplers(this, maxTextureUnits);
    }

    /**
     * Returns the number of texture units this shader was built to support.
     *
     * <p>
     * This value should match the texture unit configuration expected by the
     * {@link TextureBatch} that uses this shader.
     * </p>
     *
     * @return the supported texture unit count
     */
    public int getMaxTextureUnits() {
        return maxTextureUnits;
    }

    /**
     * Normalizes the supplied vertex shader source.
     *
     * <p>
     * If the provided source is null or blank, the default batch vertex shader is returned. Otherwise
     * the provided source is returned unchanged.
     * </p>
     *
     * @param vertexSource the custom vertex shader source, or null
     * @return the final vertex shader source that should be passed to the base shader constructor
     */
    private static String normalizeVertexSource(String vertexSource) {
        return vertexSource == null || vertexSource.isBlank() ? TextureBatchContract.defaultVertexShader() : vertexSource;
    }

    /**
     * Normalizes the supplied fragment shader source.
     *
     * <p>
     * This method applies the following rules:
     * </p>
     * <ul>
     *     <li>If the fragment source is null or blank, a complete default batch fragment shader is built</li>
     *     <li>If {@code fullFragmentSource} is true, the provided source is used exactly as-is</li>
     *     <li>Otherwise, the standard batch fragment preamble is prepended to the provided fragment body</li>
     * </ul>
     *
     * @param fragmentSource     the fragment shader source or shader body
     * @param maxTextureUnits    the number of texture samplers that must be declared
     * @param fullFragmentSource whether the supplied source is already a complete fragment shader
     * @return the final fragment shader source that should be passed to the base shader constructor
     */
    private static String normalizeFragmentSource(String fragmentSource, int maxTextureUnits, boolean fullFragmentSource) {
        if (fragmentSource == null || fragmentSource.isBlank()) {
            return TextureBatchContract.buildDefaultFragmentShader(maxTextureUnits);
        }

        if (fullFragmentSource) {
            return fragmentSource;
        }

        return TextureBatchContract.buildFragmentPreamble(maxTextureUnits) + fragmentSource;
    }
}